import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"

/**
 * @openapi
 * /api/digest:
 *   get:
 *     summary: Get the AI-generated daily digest summarizing top discussions, matches, and standings
 *     tags: [Digest]
 *     parameters:
 *       - in: query
 *         name: date
 *         schema:
 *           type: string
 *           format: date
 *         example: "2026-03-08"
 *       - in: query
 *         name: force
 *         schema:
 *           type: boolean
 *         example: false
 *     responses:
 *       200:
 *         description: Daily digest content, or empty result if no digest exists for the requested date
 *       500:
 *         description: Internal server error
 */

/**
 * GET /api/digest
 *
 * User Story:
 *   As a user, I want to read a daily digest post generated by AI that
 *   summarizes the top discussions, recorded matches, and standings,
 *   allowing me to quickly catch up on recent events.
 *
 * Behavior:
 * - Returns today's cached digest if it already exists.
 * - Otherwise gathers fresh data, asks the AI to summarize it,
 *   caches the result, and returns it.
 *
 * Query params:
 *   ?date=YYYY-MM-DD   (optional, defaults to today)
 *   ?force=true         (optional, regenerate even if cached)
 */

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url)
    const dateParam = searchParams.get("date")
    const force = searchParams.get("force") === "true"

    const todayStr = new Date().toISOString().slice(0, 10) // "YYYY-MM-DD"
    const today = dateParam ?? todayStr

    // ── Return cached digest unless forced ────────────
    if (!force) {
      const existing = await prisma.dailyDigest.findUnique({
        where: { date: today },
      })
      if (existing) {
        return NextResponse.json(existing)
      }
    }

    // ── Past dates with no cache → 200 with empty result ─
    // Only generate fresh digests for today. Historical dates without a
    // cached entry return an empty response — the resource is valid but
    // had no content for that day.
    if (today !== todayStr) {
      return NextResponse.json({
        date: today,
        content: null,
        generatedAt: null,
        message: `No digest found for ${today}`,
      })
    }

    // ── Gather data for the digest ────────────────────

    // 1. Recent match results (last 7 days)
    const sevenDaysAgo = new Date()
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7)

    const recentMatches = await prisma.match.findMany({
      where: {
        matchDate: { gte: sevenDaysAgo },
        status: "FINISHED",
      },
      include: {
        homeTeam: { select: { name: true, shortName: true } },
        awayTeam: { select: { name: true, shortName: true } },
      },
      orderBy: { matchDate: "desc" },
      take: 10,
    })

    // 2. Upcoming matches (next 7 days)
    const sevenDaysAhead = new Date()
    sevenDaysAhead.setDate(sevenDaysAhead.getDate() + 7)

    const upcomingMatches = await prisma.match.findMany({
      where: {
        matchDate: { gte: new Date(), lte: sevenDaysAhead },
        status: { in: ["SCHEDULED", "TIMED"] },
      },
      include: {
        homeTeam: { select: { name: true, shortName: true } },
        awayTeam: { select: { name: true, shortName: true } },
      },
      orderBy: { matchDate: "asc" },
      take: 5,
    })

    // 3. Current standings
    const currentSeason = String(new Date().getFullYear() - 1)
    const allStandings = await prisma.standing.findMany({
      where: { season: currentSeason, type: "TOTAL" },
      include: { team: { select: { name: true } } },
      orderBy: { position: "asc" },
    })

    const topStandings = allStandings.slice(0, 5)
    const bottomStandings = allStandings.length > 3 ? allStandings.slice(-3) : []

    // 4. Trending discussion threads (most posts)
    const trendingThreads = await prisma.thread.findMany({
      where: { isHidden: false },
      include: {
        author: { select: { username: true } },
        _count: { select: { posts: true } },
        tags: { include: { tag: true } },
        team: { select: { name: true } },
      },
      orderBy: { posts: { _count: "desc" } },
      take: 5,
    })

    // 5. Most active users today
    const oneDayAgo = new Date()
    oneDayAgo.setDate(oneDayAgo.getDate() - 1)

    const activeUsers = await prisma.user.findMany({
      where: { isBanned: false },
      include: {
        _count: {
          select: {
            posts: { where: { createdAt: { gte: oneDayAgo } } },
            replies: { where: { createdAt: { gte: oneDayAgo } } },
          },
        },
      },
      take: 50,
    })

    const topActiveUsers = activeUsers
      .map((u) => ({
        username: u.username ?? "anonymous",
        activity: u._count.posts + u._count.replies,
      }))
      .filter((u) => u.activity > 0)
      .sort((a, b) => b.activity - a.activity)
      .slice(0, 3)

    // ── Build structured digest ────────────────────────
    const content = buildStructuredDigest(
      today,
      recentMatches,
      upcomingMatches,
      topStandings,
      bottomStandings,
      trendingThreads,
      topActiveUsers
    )

    // ── Cache and return ─────────────────────────────
    const digest = await prisma.dailyDigest.upsert({
      where: { date: today },
      update: { content, generatedAt: new Date() },
      create: { date: today, content },
    })

    return NextResponse.json(digest)
  } catch (error) {
    console.error("Digest generation error:", error)
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    )
  }
}

// ─── Structured digest builder ───────────────────────────────────

function buildStructuredDigest(
  date: string,
  recentMatches: Array<{
    homeTeam: { name: string; shortName: string }
    awayTeam: { name: string; shortName: string }
    homeScore: number | null
    awayScore: number | null
    matchDate: Date
    stage: string
    matchday: number
  }>,
  upcomingMatches: Array<{
    homeTeam: { name: string; shortName: string }
    awayTeam: { name: string; shortName: string }
    matchDate: Date
    stage: string
    matchday: number
  }>,
  topStandings: Array<{
    position: number
    team: { name: string }
    points: number
    played: number
    won: number
    drawn: number
    lost: number
    goalsFor: number
    goalsAgainst: number
  }>,
  bottomStandings: Array<{
    position: number
    team: { name: string }
    points: number
    played: number
    won: number
    drawn: number
    lost: number
    goalsFor: number
    goalsAgainst: number
  }>,
  threads: Array<{
    id: string
    title: string
    author: { username: string | null }
    _count: { posts: number }
    tags: Array<{ tag: { name: string } }>
    team: { name: string } | null
  }>,
  activeUsers: Array<{ username: string; activity: number }>
): string {
  const dateDisplay = new Date(date).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  const sections: string[] = []

  // ── Header ──────────────────────────────────────────
  sections.push(`# SportsDeck Daily Digest\n### ${dateDisplay}`)

  // ── Recent Results ───────────────────────────────────
  if (recentMatches.length > 0) {
    let s = "## ⚽ Recent Results\n\n"
    s += "| Date | Home | Score | Away | Stage |\n"
    s += "|------|------|-------|------|-------|\n"
    for (const m of recentMatches) {
      const d = m.matchDate.toLocaleDateString("en-US", { month: "short", day: "numeric" })
      const score = `**${m.homeScore ?? "?"}** – **${m.awayScore ?? "?"}**`
      const winner =
        m.homeScore !== null && m.awayScore !== null
          ? m.homeScore > m.awayScore
            ? `**${m.homeTeam.shortName}**`
            : m.awayScore > m.homeScore
              ? `**${m.awayTeam.shortName}**`
              : "Draw"
          : "–"
      s += `| ${d} | ${m.homeTeam.name} | ${score} | ${m.awayTeam.name} | MD ${m.matchday} |\n`
      void winner
    }
    sections.push(s)
  } else {
    sections.push("## ⚽ Recent Results\n\nNo matches completed in the last 7 days.")
  }

  // ── Upcoming Fixtures ────────────────────────────────
  if (upcomingMatches.length > 0) {
    let s = "## 📅 Upcoming Fixtures\n\n"
    s += "| Date | Home | vs | Away | Stage |\n"
    s += "|------|------|----|------|-------|\n"
    for (const m of upcomingMatches) {
      const d = m.matchDate.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })
      const t = m.matchDate.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })
      s += `| ${d} ${t} | ${m.homeTeam.name} | vs | ${m.awayTeam.name} | MD ${m.matchday} |\n`
    }
    sections.push(s)
  }

  // ── Standings ────────────────────────────────────────
  if (topStandings.length > 0) {
    let s = "## 🏆 Standings — Top 5\n\n"
    s += "| Pos | Team | Pts | P | W | D | L | GF | GA | GD |\n"
    s += "|-----|------|-----|---|---|---|---|----|----|----|\n"
    for (const st of topStandings) {
      const gd = st.goalsFor - st.goalsAgainst
      const gdStr = gd > 0 ? `+${gd}` : `${gd}`
      s += `| ${st.position} | ${st.team.name} | **${st.points}** | ${st.played} | ${st.won} | ${st.drawn} | ${st.lost} | ${st.goalsFor} | ${st.goalsAgainst} | ${gdStr} |\n`
    }
    sections.push(s)
  }

  if (bottomStandings.length > 0) {
    let s = "## 🔻 Relegation Zone\n\n"
    s += "| Pos | Team | Pts | P | W | D | L | GD |\n"
    s += "|-----|------|-----|---|---|---|---|----|\n"
    for (const st of bottomStandings) {
      const gd = st.goalsFor - st.goalsAgainst
      const gdStr = gd > 0 ? `+${gd}` : `${gd}`
      s += `| ${st.position} | ${st.team.name} | **${st.points}** | ${st.played} | ${st.won} | ${st.drawn} | ${st.lost} | ${gdStr} |\n`
    }
    sections.push(s)
  }

  // ── Trending Discussions ─────────────────────────────
  if (threads.length > 0) {
    let s = "## 💬 Trending Discussions\n\n"
    for (const t of threads) {
      const tags = t.tags.map((tt) => `\`#${tt.tag.name}\``).join(" ")
      const forum = t.team ? `${t.team.name} forum` : "General forum"
      s += `### [${t.title}](/threads/${t.id})\n`
      s += `**${t._count.posts}** posts · by **${t.author.username ?? "anonymous"}** · ${forum}\n`
      if (tags) s += `\n${tags}\n`
      s += "\n"
    }
    sections.push(s)
  } else {
    sections.push("## 💬 Trending Discussions\n\nNo active discussions today.")
  }

  // ── Most Active Users ────────────────────────────────
  if (activeUsers.length > 0) {
    let s = "## 🔥 Most Active Today\n\n"
    for (let i = 0; i < activeUsers.length; i++) {
      const medal = i === 0 ? "🥇" : i === 1 ? "🥈" : "🥉"
      s += `${medal} **${activeUsers[i].username}** — ${activeUsers[i].activity} contribution${activeUsers[i].activity !== 1 ? "s" : ""}\n`
    }
    sections.push(s)
  }

  return sections.join("\n\n---\n\n")
}
